services:

  backend:
    working_dir: /root/app
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/root/app
    restart: always
    tty: true
    stdin_open: true
    command: python3 api.py
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/root/app
      - node_modules:/root/app/node_modules
    restart: always
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules: