version: "3"

services:

  backend:
    working_dir: /root/app
    build:
      context: ./.docker/backend/
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/root/app
    restart: always
    tty: true
    stdin_open: true
    command: python api.py