version: "3"

services:

  backend:
    build:
      context: ./docker/backend/
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/app
    restart: always
    tty: true
    stdin_open: true
    command: sleep infinity