version: "3"

services:

  app:
    build:
      context: .
    # ports:
    #   - "3000:3000"
    # volumes:
    #   - ./web:/app
    #   - node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true
    command: sleep infinity
# volumes:
#   node_modules: